; software/Mimic/examples/BasicRead/platformio.ini

[env:uno_r4_minima]
platform = renesas-ra
board = uno_r4_minima
framework = arduino

[platformio]
src_dir = . ; このフォルダの .ino を直接ビルド対象にする

[env]
; 親階層の Mimic 自体をライブラリとして認識させる
lib_extra_dirs = ../../../

build_flags = 
    -I../../../../firmware/core/Inc

monitor_speed = 115200
